services:
  - type: web
    name: sidian-website
    rootDir: sidian_website
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: node dist/sidian_website/server/server.mjs
    envVars:
      - key: NODE_ENV
        value: production
